services:
  pythonapp:
    build: ./pythonapp/
    tty: true
    command:  sh -c "sleep 10s ; python3 ./main.py;"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABSE: 'Stori'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
